### ISSUE TITLE
_self_keys.dart不存在，是文件没提交吗？

### ISSUE THREAD

**Issue by wookkkkk** [Sanotsu/free-fitness#6]
lib/apis/paid_llm_apis.dart这个文件
另外，安装[0.2.0-beta.1]这个版本，导入[yuhonas/free-exercise-db]这个项目的基础动作后，文字内容正常，图片不能显示

**Comment by Sanotsu** [comment]
@wookkkkk 
1. _self_keys.dart部分
_self_keys.dart是我放零一万物api key的文件，用于放置个人申请的key，忘了说明了，结构如下:
```dart
import '../models/paid_llm/common_chat_model_spec.dart';

final Map<ApiPlatform, String> cusAKMap = {
  ApiPlatform.lingyiwanwu: 'xxxx',
};
```

2. 动作及其图片导入部分
假设你下载了[yuhonas/free-exercise-db](https://github.com/yuhonas/free-exercise-db)的zip包，解压应该是这个样子：
![Snipaste_2024-11-11_08-31-45](https://github.com/user-attachments/assets/be3ba7f8-0510-45f0-8409-b3e368c27bda)

在应用中，假如将free-exercise-db在根目录进行的解压
- 选择导入json文件，选中dist中的exercises.json文件
- 选择对应图片所在的文件夹，即exercises文件夹

在导入页面就应该如下图显示
![导入界面截图](https://github.com/user-attachments/assets/9e6d5454-aa29-4d93-b3f8-1de88e4280a8)

按照这个操作之后，只要显示导入成功，动作应该是这个画面：
![导入成功截图](https://github.com/user-attachments/assets/52551d63-1afd-4d30-a698-3b72af6b5470)

后续有空我再优化下步骤和说明。

**Comment by wookkkkk** [comment]
感谢解答，非常清晰，已解决问题。
我之前操作时只导入了exercises文件夹，未导入exercises.json文件，是我的操作问题导致图片不能正确加载。
另外描述一下我的操作：我因为之前导入了exercises文件夹并保存，后续重新导入json后会提示动作已存在，我尝试了几次也不成功，只能卸载重装app解决。
最后，再次感谢您的解答和开源。
